server:
  port: 9009
spring:
  application:
    name: zipkin-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/     #注册中心地址
management:
  metrics:
    web:
      server:
        auto-time-requests: false           #关闭自动收集web请求