server:
  port: 8060
spring:
  application:
    name: allzuul
  zipkin:
    base-url: http://localhost:9009/
    sleuth:
      sampler:
        probability: 1.0
eureka:
  instance:
    instance-id: allzuul-8060
    prefer-ip-address: true
  client:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    service-url:
      defaultZone: http://localhost:8761/eureka/


#zuul:
#  routes:
#    eureka-ribbon: #对应服务名称,可以自定义（最好保持一致）
#     path: /ribbon/*
#     serviceId: eureka-ribbon #对应服务名称
#    eureka-feign:
#      path: /Takeaway/*
#      serviceId: allclient #对应服务名称
zuul:        #配置Zuul设置
  routes:
    allclient:
      path: /**    #Zuul路由的前缀
  host:       #超时设置
    socket-timeout-millis: 60000
    connect-timeout-millis: 10000