server:
  port: 8040
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  application:
    name: user
  zipkin:
    base-url: http://localhost:9009/
    sleuth:
      sampler:
        probability: 1.0
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/orderingsystem?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: user-8040
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:/mybatis/*.xml
  type-aliases-package: com.snowy.southwind.bean
